### ISSUE TITLE
parameter incorrect. 

### ISSUE THREAD

**Issue by ulao** [MightyDevices/MightyHID#5]
Hi just set everything up but get parameter incorrect. on this line.
 _fileStream.Write(data, 0, data.Length);

any ideas?

error:
An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll
Additional information: The parameter is incorrect.

This normally is a sharing issue but I don't see what would be using this stream. 

Also this is a gamepad device I created with reports I use with HID.dll already (c command line tool)

**Comment by jpmcm** [comment]
I have this problem too....

All HID devices are display in console, then when generating the reports it fails on the first Write to the filestream and throws 'System.IO.IOException'. See below stackstrace

System.IO.IOException was unhandled
  HResult=-2147024809
  Message=The parameter is incorrect.

  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.EndWrite(IAsyncResult asyncResult)
       at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
       at Mighty.HID.HIDDev.Write(Byte[] data) in C:\Users\xxxxxxxx\Downloads\MightyHID-master\MightyHID-master\MightyHID\MightyHID\HIDDev.cs:line 87
       at MightyHIDTest.Program.Main(String[] args) in C:\Users\xxxxxxx\Downloads\MightyHID-master\MightyHID-master\MightyHIDTest\MightyHIDTest\Program.cs:line 36
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by skunx99** [comment]
I had to jump ship on this and I found https://github.com/signal11/hidapi  to work better.
